# Compose para nuvem digital ocean
version: "3"
services:
  api-node-01:
    image: registry.digitalocean.com/dcr-samuel/puc-node-api-01:${TAG}
    container_name: puc-node-api-01
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        - TAG=${TAG}
    ports:
      - "3000:3000"


# Compose para LOCALHOST
#version: "3"
#services:
#  api-node-01:
#    image: puc-node-api-1
#    container_name: puc-node-api-1
#    build: .
#    expose:
#      - "3000"
#    ports:
#      - "3000:3000"