version: "3"
services:
  api-node-01:
    image: registry.digitalocean.com/dcr-samuel/puc-node-api-01:${TAG}
    container_name: puc-node-api-01
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        - TAG=${TAG}
    #working_dir: /home/node/app
    #environment:
    #  - NODE_ENV=production
    expose:
      - "3000"
    ports:
      - "3000:3000"


# O bloco abaixo para executar localhost
# version: "3"
# services:
#   api:
#     build: .
#     working_dir: /home/node/app
#     expose:
#       - "3000"
#     ports:
#       - "3000:3000"